AWSTemplateFormatVersion: '2010-09-09'
Description: Checks available % of IP addresses within subnets
Resources:
  CheckIPsAvailable:
    Properties:
      CodeUri: s3://mels3skobucket/LambdaFunction/76f5a5e72c6ed74e3301284f7286a8a5
      Description: Checks percentage of available IP address within a subnet
      Environment:
        Variables:
          MESSAGE_SUBJECT: You have subnets running out of available ip addresses!
          PERCENTAGE_WARNING: '20'
          REGION_ID: ''
          TARGET_ARN:
            Ref: IPAddressExahustionSNSTopic
          VPC_ID: ''
      FunctionName: Lambda_Check_Available_IP_Address_Space
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role:
        Fn::GetAtt:
        - IPAddressCheckLambdaRole
        - Arn
      Runtime: python3.6
      Timeout: 120
    Type: AWS::Serverless::Function
  IPAddressCheckLambdaRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - ec2:DescribeSubnets
            - ec2:DescribeVpcs
            - ec2:DescribeVpcAttribute
            - ec2:DescribeRegions
            Effect: Allow
            Resource: '*'
          - Action: sns:Publish
            Effect: Allow
            Resource:
              Ref: IPAddressExahustionSNSTopic
          - Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Effect: Allow
            Resource: '*'
          Version: '2012-10-17'
        PolicyName: IP_Address_Check_Lambda_Policy
      RoleName: IP_Address_Check_Lambda_Role
    Type: AWS::IAM::Role
  IPAddressExahustionSNSTopic:
    Properties:
      DisplayName: Notification of IP Exhaustion
      TopicName: IPAddressExahustion
    Type: AWS::SNS::Topic
  PermissionForEventsToInvokeLambda:
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: CheckIPsAvailable
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
        - ScheduledRule
        - Arn
    Type: AWS::Lambda::Permission
  ScheduledRule:
    Properties:
      Description: ScheduledRule
      Name: Lambda_Check_Available_IP_Addresses
      ScheduleExpression: rate(8 hours)
      State: DISABLED
      Targets:
      - Arn:
          Fn::GetAtt:
          - CheckIPsAvailable
          - Arn
        Id: TargetFunctionV1
    Type: AWS::Events::Rule
Transform: AWS::Serverless-2016-10-31
